### ISSUE TITLE
onenote onedrive

### ISSUE THREAD

**Issue by Tory73** [th3power/aegis-voat#4]
Hi,

Thanks for this tool!

I use Windows 7. With version 1.16 of your tool I'm able to go to the Microsoft pages again. The thing that don't work is connect through my onenote to my onedrive. When I trying to login on onenote to onedrive it gives a blanco screen after entering my hotmail account. When I use the unblock version of your script it works again.

I have no idea if that is ment to be and is using onedrive 'not done and don't use it all', but if it is safe to use do you have any idea how I can fix this without blocking all what your schrips have blocked, or do you have plans to make a version that does not block this option I described.

**Comment by th3power** [comment]
We have intentionally blocked onedrive/skydrive (see list of blocked/disabled components in README.md) however I am open to helping you figure out how to unblock it on your own system. I will do some research about this and reply back to you soon.

**Comment by Tory73** [comment]
Thanks th3power, that will be great! If you also have installed onenote you can see exactly what I mean. I like onenote, and onedrive is the best options to sync when I work and share a document with another person. It can also be done with dropbox, but it is not optimal.

Thanks for the support and when you're ready with the research I'm happy to read your solution for my case, but take your time of course.

**Comment by th3power** [comment]
Try removing this registry key:

HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Skydrive\DisableFileSync

If it still doesn't work let me know and I will look at other possible causes

**Comment by th3power** [comment]
I am going to close this issue as the op has not responded for a while and I believe my answer addresses the issue. If you still have a problem please re-open this issue or make a new one.
