### ISSUE TITLE
aegis v1.18 really slow - 66 mins to complete

### ISSUE THREAD

**Issue by Geyup** [th3power/aegis-voat#9]
Hello,

First let me say thanks for creating this, seems really nice.

But when I ran this in Windows 7 x64 Home Premium it tooks 66 mins to complete.

This seems like an extreme amount of time to complete.

Also under the Windows Update, before running aegis, it would show with the green icon checkmark saying, Windows is up to date.

After running aeigs and then rebooting, when I came back and looked at the updates section, I noticed the history was gone and now Windows was displaying the red icon with the X saying, Check for updates for your computer, and that there had never been any updates.

I don't want this history killed off like this, I hope you can please fix this, or tell me what's causing it.

But I'm not looking forward to running this and waiting another 66 mins.

Thanks

**Comment by th3power** [comment]
This is not unheard of on slower systems (especially if you don't have a ssd). It usually takes much longer the first time/few times you run it. Once you get the system cleaned up it should only take a few minutes to run. And it should not reset your update history each time. I would also advise you to follow our recommended procedures for the best results.

The recommended procedure for applying updates on a fresh install is:

1> Download and install kb3050265 (or kb3050267 on Windows 8):
2> Reboot
3> Run 'repairwindowsupdate.cmd' (right click, run as admin)
4> Check for updates
5> Run Aegis
6> Install updates
7> Reboot
8> Repeat 4-7

The recommended procedure for applying updates on an ongoing basis is:
1> Check for updates
2> Run Aegis
3> Install updates
4> Reboot
5> Repeat 1-4

**Comment by Geyup** [comment]
I'm a Linux geek, so I set up Windows 7 the way I setup and backup Linux.

I installed Windows 7, then I updated it, and installed a few apps, next I created a clonezilla backup of this system in a clean state, then I ran Aegis, in this order I don't see how this is any different from what you've explained...

I also have a pretty fast system.

Intel i7-3610QM CPU @ 2.30GHz - It will also run to 3GHz
12GB DD3 - 1600 MHz
Samsung 850 Pro 128GB SSD

Given the specs on my system I don't expect something like this to of taken this long...
